dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: godigital-angular
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: pim-product
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.0
- name: subscription
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.27
- name: subscription-node-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
